### ISSUE TITLE
Components disappear from lockscreen after Control Center 

### ISSUE THREAD

**Issue by MindScape00** [midnightchip/Asteroid#56]
When on the lockscreen, if you open and then close Control Center, this will cause all the components to disappear. The background animations of weather still work though. Unlocking / relocking or just turning the screen off and on again makes them reappear again but it makes it impossible to open control center to start screen recording and then capture the lockscreen with the components shown.

**Comment by the-casle** [comment]
Long story short the media player in the cc triggers the view to be hidden. Im not really sure we can fix this because messing with the media player (it works with no issues so far) has the chance of of unsyncing with the notifications and they remain hidden. 

You can go on the homescreen, hit screen record and lock - unlock the device before the 3 sec countdown and it will record.
